import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('titanic.csv')

num_passageiros = len(df)
num_mulheres = df[df['Sex'] == 'female']['PassengerId'].count()
num_homens = df[df['Sex'] == 'male']['PassengerId'].count()
m_idade = df['Age'].mean()
m_idade_mulheres = df[df['Sex'] == 'female']['Age'].mean()
m_idade_homens = df[df['Sex'] == 'male']['Age'].mean()
homens_45_mais = df[(df['Sex'] == 'male') & (df['Age'] > 45)]['PassengerId'].count()
mulheres_25_menos = df[(df['Sex'] == 'female') & (df['Age'] < 25)]['PassengerId'].count()
homens_primeira_classe = df[(df['Sex'] == 'male') & (df['Pclass'] == 1)]['PassengerId'].count()
homens_segunda_classe = df[(df['Sex'] == 'male') & (df['Pclass'] == 2)]['PassengerId'].count()
homens_terceira_classe = df[(df['Sex'] == 'male') & (df['Pclass'] == 3)]['PassengerId'].count()
mulheres_primeira_classe = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]['PassengerId'].count()
mulheres_segunda_classe = df[(df['Sex'] == 'female') & (df['Pclass'] == 2)]['PassengerId'].count()
mulheres_terceira_classe = df[(df['Sex'] == 'female') & (df['Pclass'] == 3)]['PassengerId'].count()

plt.figure(figsize=(12, 6))
plt.hist(df[df['Pclass'] == 1]['Age'], bins=20, color='blue', alpha=0.5, label='1ª Classe')
plt.hist(df[df['Pclass'] == 2]['Age'], bins=20, color='green', alpha=0.5, label='2ª Classe')
plt.hist(df[df['Pclass'] == 3]['Age'], bins=20, color='red', alpha=0.5, label='3ª Classe')
plt.xlabel('Idade')
plt.ylabel('Número de Passageiros')
plt.legend()
plt.title('Histograma de Idades por Classe')
plt.show()

plt.figure(figsize=(12, 6))
plt.hist(df[(df['Pclass'] == 1) & (df['Sex'] == 'male')]['Age'], bins=20, color='blue', alpha=0.5, label='Homens')
plt.hist(df[(df['Pclass'] == 1) & (df['Sex'] == 'female')]['Age'], bins=20, color='pink', alpha=0.5, label='Mulheres')
plt.xlabel('Idade')
plt.ylabel('Número de Passageiros')
plt.legend()
plt.title('Histograma de Idades de Homens e Mulheres da Primeira Classe')
plt.show()

plt.figure(figsize=(12, 6))
plt.hist(df[(df['Pclass'] == 2) & (df['Sex'] == 'male')]['Age'], bins=20, color='blue', alpha=0.5, label='Homens')
plt.hist(df[(df['Pclass'] == 2) & (df['Sex'] == 'female')]['Age'], bins=20, color='pink', alpha=0.5, label='Mulheres')
plt.xlabel('Idade')
plt.ylabel('Número de Passageiros')
plt.legend()
plt.title('Histograma de Idades de Homens e Mulheres da Segunda Classe')
plt.show()
plt.figure(figsize=(12, 6))
plt.hist(df[(df['Pclass'] == 3) & (df['Sex'] == 'male')]['Age'], bins=20, color='blue', alpha=0.5, label='Homens')
plt.hist(df[(df['Pclass'] == 3) & (df['Sex'] == 'female')]['Age'], bins=20, color='pink', alpha=0.5, label='Mulheres')
plt.xlabel('Idade')
plt.ylabel('Número de Passageiros')
plt.legend()
plt.title('Histograma de Idades de Homens e Mulheres da Terceira Classe')
plt.show()

print("Número de passageiros:", num_passageiros)
print("Número de mulheres a bordo:", num_mulheres)
print("Número de homens a bordo:", num_homens)
print("Média de idade dos passageiros:", m_idade)
print("Média de idade das mulheres a bordo:", m_idade_mulheres)
print("Média de idade dos homens a bordo:", m_idade_homens)
print("Número de homens a bordo com idade acima de 45 anos:", homens_45_mais)
print("Número de mulheres a bordo com idade abaixo de 25 anos:", mulheres_25_menos)
print("Número de homens na primeira classe:", homens_primeira_classe)
print("Número de mulheres na primeira classe:", mulheres_primeira_classe)
print("Número de homens na segunda classe:", homens_segunda_classe)
print("Número de mulheres na segunda classe:", mulheres_segunda_classe)
print("Número de homens na terceira classe:", homens_terceira_classe)
print("Número de mulheres na terceira classe:", mulheres_terceira_classe)
